spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      url: ${VALKEY_URL}

app:
  security:
    initial-user:
      username: ${APP_INITIAL_USER_USERNAME}
      password: ${APP_INITIAL_USER_PASSWORD}
